ALTER USER db_admin WITH ENCRYPTED PASSWORD 'db_admin_password';

GRANT CONNECT, TEMPORARY ON DATABASE musicly TO db_admin;

GRANT ALL PRIVILEGES ON SCHEMA public TO db_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO db_admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO db_admin;
