# Generated by Django 3.1.5 on 2021-03-12 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicly', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('account', 'name')},
        ),
    ]
