# Generated by Django 3.1.5 on 2021-03-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicly', '0002_auto_20210312_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='length',
            field=models.IntegerField(default=0, verbose_name='Total playtime of the playlist playlist'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='music_count',
            field=models.IntegerField(default=0, verbose_name='Number of recordings in the playlist'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
