# Generated by Django 3.1.5 on 2021-09-10 18:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicly', '0002_auto_20210823_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicRecommendations',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='musicly.account')),
                ('recommendations', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=30)),
            ],
            options={
                'db_table': 'musicly_music_recommencations',
                'managed': True,
            },
        ),
    ]
