# Generated by Django 3.1.5 on 2021-09-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicly', '0003_musicrecommendations'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='musicrecommendations',
            table='musicly_music_recommendations',
        ),
    ]
