# Generated by Django 3.1.5 on 2021-03-13 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicly', '0003_auto_20210313_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='recording',
            new_name='recordings',
        ),
    ]
