# Generated by Django 3.1.5 on 2021-03-13 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicly', '0005_auto_20210313_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistmusic',
            options={'managed': True},
        ),
    ]
